users:
  name_length: 50
  email_length: 255
  pass_min_length: 6
  avatar_size: 80
  per_page: 10
  pass_expire: 2
  avatar_follower: 30
microposts:
  content_length: 140
  avatar_size: 50
  img_upload_size: [400, 400]
  max_size: 5
conditions:
  checked: "1"
mails:
  from: "noreply@example.com"
